### ISSUE TITLE
drush updb without `-y` will break build-process

### ISSUE THREAD

**Issue by stmh** [amazeeio/drupal7-example#1]
https://github.com/amazeeio/drupal7-example/blob/626de1171eab57501f1ca11add4c8a4986c7edec/.lagoon.yml#L19

**Comment by ChandeepKhosa** [comment]
I have a new Drupal 7 site I've migrated to Lagoon and my builds aren't breaking. I'm also not seeing anything in the logs relating to this. I advise we close this issue unless `stmh` is still experiencing it

**Comment by ChandeepKhosa** [comment]
Thanks for this, I ran into the same issue today and this change fixed it. I've created a Pull Request with this change which the amazee.io team will merge in soon, so we can now close out this issue
